# Sample of a Glance CR where quotas are customized
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  glance:
    template:
      serviceUser: glance
      databaseInstance: openstack
      databaseAccount: glance
      keystoneEndpoint: default
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = default_backend:swift
        [glance_store]
        default_backend = default_backend
        [default_backend]
        swift_store_create_container_on_put = True
        swift_store_auth_version = 3
        swift_store_auth_address = {{ .KeystoneInternalURL }}
        swift_store_endpoint_type = internalURL
        swift_store_user = service:glance
        swift_store_key = {{ .ServicePassword }}
      glanceAPIs:
        default:
          replicas: 1
          type: split
      secret: osp-secret
      storage:
        storageRequest: 10G
      quotas:
        imageSizeTotal: 1000
        imageStageTotal: 1000
        imageCountUpload: 100
        imageCountTotal: 100
