# Sample using Ceph as a glance backend with image decompression plugin
# Requires a running Ceph cluster and its `/etc/ceph` files in secret `ceph-conf-files`
# This can be achieved with the `ceph` target of `install_yamls`
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  glance:
    template:
      databaseInstance: openstack
      serviceUser: glance
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = default_backend:rbd
        [glance_store]
        default_backend = default_backend
        [default_backend]
        rbd_store_ceph_conf = /etc/ceph/ceph.conf
        store_description = "RBD backend"
        rbd_store_pool = images
        rbd_store_user = openstack
        [image_import_opts]
        image_import_plugins = [image_decompression]
      databaseAccount: glance
      glanceAPIs:
        default:
          preserveJobs: false
          replicas: 1
      secret: osp-secret
      storage:
        storageClass: ""
        storageRequest: 1G
      extraMounts:
        - name: v1
          region: r1
          extraVol:
            - extraVolType: Ceph
              volumes:
              - name: ceph
                secret:
                  name: ceph-conf-files
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true
