apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  glance:
    template:
      serviceUser: glance
      customServiceConfig: |
        [oslo_policy]
        policy_file=/etc/glance/policy.d/policy.yaml
        enforce_scope=true
        enforce_new_defaults=true
      databaseInstance: openstack
      databaseAccount: glance
      glanceAPIs:
        default:
          replicas: 1
      secret: osp-secret
      storage:
        storageRequest: 10G
      extraMounts:
        - name: v1
          region: r1
          extraVol:
            - extraVolType: Policy
              volumes:
                - name: glance-policy
                  configMap:
                    name: glance-policy
              mounts:
                - name: glance-policy
                  mountPath: /etc/glance/policy.d/
                  readOnly: true
