resources:
- ../backends/base/openstack

patches:
- path: glance_policy.yaml

configMapGenerator:
- files:
  - ./policy.yaml
  name: glance-policy

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
