apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseAccount: glance
  keystoneEndpoint: central
  glanceAPIs:
    edge1:
      preserveJobs: false
      replicas: 1
      type: edge
    edge2:
      preserveJobs: false
      replicas: 1
      type: edge
    central:
      preserveJobs: false
      replicas: 1
      type: single
  secret: osp-secret
  storage:
    storageClass: local-storage
    storageRequest: 10G
